// packages/wisspop/src/vue/WissPopFlip.vue
<template>
  <div class="wisspop-flip-trigger-wrapper">
    <!--
      Sin `v-show`: lo esconde con `display: none`, que lo saca del layout — la
      página de abajo salta mientras el modal está abierto, y su rect pasa a ser
      0x0, así que el cierre no tendría a dónde volver. Ocultarlo es del core,
      que usa `visibility: hidden`: invisible pero conservando su lugar.
    -->
    <div
      ref="triggerEl"
      class="wisspop-flip-trigger"
      :class="{ 'wisspop-clickable': triggerClickable }"
      @click="triggerClickable ? open() : undefined"
    >
      <slot name="trigger" :open="open" />
    </div>

    <Teleport to="body">
      <div
        v-if="visible && overlay"
        ref="overlayEl"
        class="wisspop-overlay"
        :class="[
          overlayBlur && 'wisspop-overlay-blur',
          overlayDark && 'wisspop-overlay-dark',
          overlayClass
        ]"
        @click="close"
      />
      <div
        v-if="visible"
        ref="boxEl"
        class="wisspop-box wisspop-flip-box"
        :class="modalClass"
        @click.stop
      >
        <slot name="modal" :close="close" />
        <button
          v-if="closeButton"
          type="button"
          class="wisspop-close"
          :class="closeButtonClass"
          aria-label="Cerrar"
          @click="close"
        >
          <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
            <path d="M18 6 6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
    </Teleport>
  </div>
</template>

<script setup>
import { ref, watch, nextTick, onMounted, onBeforeUnmount, useAttrs } from "vue";
import { createFlip } from "../core/flip.js";
import { attrsToOptions } from "./attrs-to-options.js";
import { soloDefinidos } from "../shared/solo-definidos.js";

// Ver WissPopMorph.vue: los attrs son configuración del core.
defineOptions({ inheritAttrs: false });

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  flipId: { type: String, required: true },
  triggerClickable: { type: Boolean, default: true },
  /**
   * Velocidad y curva. Sin default propio: manda el core, así `setDefaults()`
   * puede fijar el ritmo global. Ver WissPopMorph.vue.
   */
  duration: { type: Number, default: undefined },
  ease: { type: String, default: undefined },
  overlayDuration: { type: Number, default: undefined },
  stagger: { type: Number, default: undefined },
  overlayClass: { type: String, default: "" },
  overlay: { type: Boolean, default: true },
  overlayBlur: { type: Boolean, default: false },
  overlayDark: { type: Boolean, default: false },
  modalClass: { type: String, default: "" },
  closeButton: { type: Boolean, default: false },
  closeButtonClass: { type: String, default: "" },
  closeOnEscape: { type: Boolean, default: true },
  trapFocus: { type: Boolean, default: true },
  restoreFocus: { type: Boolean, default: true },
  lockScroll: { type: Boolean, default: false },
  ariaLabel: { type: String, default: null },
  ariaLabelledby: { type: String, default: null },
});

const emit = defineEmits(["update:modelValue", "open", "close"]);

const visible = ref(false);
const triggerEl = ref(null);
const boxEl = ref(null);
const overlayEl = ref(null);

const opcionesExtra = attrsToOptions(useAttrs());

const core = createFlip(
  {
    trigger: () => triggerEl.value,
    modal: () => boxEl.value,
    overlay: () => overlayEl.value,
  },
  {
    // Primero: lo que el wrapper cablea explícitamente siempre gana.
    ...opcionesExtra,
    flipId: props.flipId,
    ...soloDefinidos({
      duration: props.duration,
      ease: props.ease,
      overlayDuration: props.overlayDuration,
      stagger: props.stagger,
    }),
    closeOnEscape: props.closeOnEscape,
    trapFocus: props.trapFocus,
    restoreFocus: props.restoreFocus,
    lockScroll: props.lockScroll,
    ariaLabel: props.ariaLabel,
    ariaLabelledby: props.ariaLabelledby,
    mount: async () => {
      visible.value = true;
      await nextTick();
    },
    unmount: () => {
      visible.value = false;
    },
    onState: (s) => {
      if (s === "opening") emit("update:modelValue", true), emit("open");
      if (s === "closed") emit("update:modelValue", false), emit("close");
    },
  },
);

const open = () => core.open();
const close = () => core.close();

watch(
  () => props.modelValue,
  (val) => (val ? core.open() : core.close()),
);

onMounted(() => props.modelValue && core.open());
onBeforeUnmount(core.destroy);

defineExpose({ open, close });
</script>

// packages/wisspop/src/react/WissPopFlip.jsx
/**
 * Wrapper React de FlipModal — mismo contrato que WissPopFlip.vue.
 * Ver WissPopMorph.jsx para las notas generales de la adaptación a React.
 */
import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import { createPortal } from "react-dom";
import { createFlip } from "../core/flip.js";
import { useDomMount } from "./use-dom-mount.js";
import { soloDefinidos } from "../shared/solo-definidos.js";

const CloseIcon = () => (
  <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
    <path d="M18 6 6 18M6 6l12 12" />
  </svg>
);

export const WissPopFlip = forwardRef(function WissPopFlip(
  {
    open: isOpen = false,
    onOpen,
    onClose,
    onOpenChange,
    flipId,
    triggerClickable = true,
    /**
     * Velocidad y curva. Sin default propio: manda el core, así `setDefaults()`
     * puede fijar el ritmo global. Ver WissPopMorph.jsx.
     */
    duration,
    ease,
    overlayDuration,
    stagger,
    overlayClass = "",
    overlay = true,
    overlayBlur = false,
    overlayDark = false,
    modalClass = "",
    closeButton = false,
    closeButtonClass = "",
    closeOnEscape = true,
    trapFocus = true,
    restoreFocus = true,
    lockScroll = false,
    ariaLabel = null,
    ariaLabelledby = null,
    /** render prop: (open) => ReactNode — lo que dispara el flip */
    trigger,
    /** render prop: (close) => ReactNode — el contenido del modal */
    children,
    /** Ver WissPopMorph.jsx: se reenvía al core, igual que `...coreOpts` de vanilla. */
    ...opcionesExtra
  },
  ref,
) {
  if (!flipId) throw new Error("[WissPopFlip] flipId es obligatorio");

  const { visible, mount, unmount } = useDomMount();
  const triggerEl = useRef(null);
  const boxEl = useRef(null);
  const overlayEl = useRef(null);
  const callbacks = useRef({ onOpen, onClose, onOpenChange });
  callbacks.current = { onOpen, onClose, onOpenChange };

  const coreRef = useRef(null);
  if (!coreRef.current) {
    coreRef.current = createFlip(
      {
        trigger: () => triggerEl.current,
        modal: () => boxEl.current,
        overlay: () => overlayEl.current,
      },
      {
        // Primero: lo que el wrapper cablea explícitamente siempre gana.
        ...opcionesExtra,
        flipId,
        ...soloDefinidos({ duration, ease, overlayDuration, stagger }),
        closeOnEscape,
        trapFocus,
        restoreFocus,
        lockScroll,
        ariaLabel,
        ariaLabelledby,
        mount,
        unmount,
        onState: (s) => {
          if (s === "opening") {
            callbacks.current.onOpenChange?.(true);
            callbacks.current.onOpen?.();
          }
          if (s === "closed") {
            callbacks.current.onOpenChange?.(false);
            callbacks.current.onClose?.();
          }
        },
      },
    );
  }

  const open = () => coreRef.current.open();
  const close = () => coreRef.current.close();

  useImperativeHandle(ref, () => ({
    open,
    close,
    get state() {
      return coreRef.current.state;
    },
  }));

  useEffect(() => {
    if (isOpen) open();
    else close();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  useEffect(() => () => coreRef.current.destroy(), []);

  return (
    <div className="wisspop-flip-trigger-wrapper">
      {/*
        Sin `display:none` (ni ocultarlo con una clase condicional): eso lo
        saca del layout y la página de abajo salta mientras el modal está
        abierto (bug encontrado y arreglado esta sesión). El core lo oculta
        con `visibility: hidden`, que conserva su lugar.
      */}
      <div
        ref={triggerEl}
        className={`wisspop-flip-trigger${triggerClickable ? " wisspop-clickable" : ""}`}
        onClick={triggerClickable ? open : undefined}
      >
        {trigger?.(open)}
      </div>

      {typeof document !== "undefined" &&
        createPortal(
          <>
            {visible && overlay && (
              <div
                ref={overlayEl}
                className={`wisspop-overlay ${overlayBlur ? "wisspop-overlay-blur" : ""} ${overlayDark ? "wisspop-overlay-dark" : ""} ${overlayClass}`.trim()}
                onClick={close}
              />
            )}
            {visible && (
              <div
                ref={boxEl}
                className={`wisspop-box wisspop-flip-box ${modalClass}`}
                onClick={(e) => e.stopPropagation()}
              >
                {children?.(close)}
                {closeButton && (
                  <button
                    type="button"
                    className={`wisspop-close ${closeButtonClass}`}
                    aria-label="Cerrar"
                    onClick={close}
                  >
                    <CloseIcon />
                  </button>
                )}
              </div>
            )}
          </>,
          document.body,
        )}
    </div>
  );
});
