// packages/wisspop/src/vue/WissPopMorph.vue
<template>
  <Teleport to="body">
    <div
      v-if="visible && overlay"
      ref="overlayEl"
      class="wisspop-overlay"
      :class="[
        overlayBlur && 'wisspop-overlay-blur',
        overlayDark && 'wisspop-overlay-dark',
        overlayClass
      ]"
      @click="requestClose"
    />
    <!-- Vive FUERA del panel: el panel es overflow-hidden mientras anima, así
         que un elemento viajero de adentro quedaría recortado durante todo el
         viaje (design.md §6). Solo se monta si el consumidor pidió texto
         viajero, igual que el `createModal` de vanilla. -->
    <div
      v-if="visible && flyingTextClass != null"
      ref="flyingEl"
      class="wisspop-flying-text"
      :class="flyingTextClass"
    />

    <div
      v-if="visible"
      ref="boxEl"
      class="wisspop-box"
      :class="modalClass"
      :style="boxStyle"
      @click.stop
    >
      <div ref="contentEl" class="wisspop-content">
        <slot :close="requestClose" />
      </div>
      <button
        v-if="closeButton"
        type="button"
        class="wisspop-close"
        :class="closeButtonClass"
        aria-label="Cerrar"
        @click="requestClose"
      >
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
          <path d="M18 6 6 18M6 6l12 12" />
        </svg>
      </button>
    </div>
  </Teleport>
</template>

<script setup>
import { ref, watch, nextTick, onMounted, onBeforeUnmount, useAttrs } from "vue";
import { createMorph } from "../core/morph.js";
import { attrsToOptions } from "./attrs-to-options.js";
import { soloDefinidos } from "../shared/solo-definidos.js";

// Los attrs son configuración del core, no atributos para el elemento raíz —
// que además no existe: el template es multi-root dentro del Teleport.
defineOptions({ inheritAttrs: false });

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  /** HTMLElement | selector CSS | Rect literal */
  originRef: { type: [Object, String], default: null },
  placement: { type: String, default: "center" },
  align: { type: String, default: "center" },
  gap: { type: Number, default: 16 },
  /**
   * Velocidad y curva. Sin default propio A PROPÓSITO: si el wrapper mandara
   * siempre un valor, pisaría al del core y `setDefaults()` no serviría de
   * nada. Sin poner nada manda el core (0.55 / 0.7, o lo que fije setDefaults).
   * El cierre tiene su propio ritmo: no es la apertura al revés.
   */
  duration: { type: Number, default: undefined },
  ease: { type: String, default: undefined },
  closeDuration: { type: Number, default: undefined },
  closeEase: { type: String, default: undefined },
  contentBlur: { type: Boolean, default: false },
  /**
   * Texto viajero. Si es `null` (default) no se monta nada y el modal se
   * comporta como antes; con cualquier string —incluso vacío— se crea el
   * elemento que viaja, misma condición que usa `createModal` de vanilla.
   */
  flyingTextClass: { type: String, default: null },
  /**
   * Qué viaja del origen al panel: un string o un nodo (se clona, el original
   * se queda en el botón). Es el default del `label` de `open()`, para que el
   * camino declarativo por `v-model` también pueda tener elemento viajero.
   */
  label: { type: [String, Object], default: null },
  labelOffsetX: { type: Number, default: 24 },
  /** `"text"` · `"box"` · `null` (automático). Ver DEFAULTS del core. */
  flyingMode: { type: String, default: null },
  /** Los estilos son del consumidor: la librería solo se ocupa del movimiento. */
  modalClass: { type: String, default: "" },
  overlayClass: { type: String, default: "" },
  overlay: { type: Boolean, default: true },
  overlayBlur: { type: Boolean, default: false },
  overlayDark: { type: Boolean, default: false },
  /** Botón × propio, para cuando no querés armar el tuyo con el `close` del slot. */
  closeButton: { type: Boolean, default: false },
  closeButtonClass: { type: String, default: "" },
  closeOnEscape: { type: Boolean, default: true },
  trapFocus: { type: Boolean, default: false },
  restoreFocus: { type: Boolean, default: true },
  lockScroll: { type: Boolean, default: false },
  ariaLabel: { type: String, default: null },
  ariaLabelledby: { type: String, default: null },
});

const emit = defineEmits(["update:modelValue", "close"]);

const visible = ref(false);
const boxStyle = ref({});
const boxEl = ref(null);
const contentEl = ref(null);
const overlayEl = ref(null);
const flyingEl = ref(null);

// Se leen una vez, igual que las props: el core se crea una sola vez.
const opcionesExtra = attrsToOptions(useAttrs());

/**
 * La geometría entra por `onGeom` a un ref reactivo en vez de que GSAP escriba
 * `boxEl.style`: si GSAP escribiera el style directo, cualquier re-render de
 * Vue reaplicaría su binding y pisaría la animación a mitad de camino
 * (design.md §2).
 *
 * Las props se leen una vez al crear el core, porque este componente abre por
 * `v-model` y no hay dónde pasar overrides. Para elegir la posición al abrir,
 * usá la API imperativa: `open()` acepta opciones por llamada.
 */
const core = createMorph(
  {
    box: () => boxEl.value,
    content: () => contentEl.value,
    overlay: () => overlayEl.value,
    flyingText: () => flyingEl.value,
  },
  {
    // Primero: lo que el wrapper cablea explícitamente siempre gana.
    ...opcionesExtra,
    placement: props.placement,
    align: props.align,
    gap: props.gap,
    ...soloDefinidos({
      duration: props.duration,
      ease: props.ease,
      closeDuration: props.closeDuration,
      closeEase: props.closeEase,
    }),
    contentBlur: props.contentBlur,
    labelOffsetX: props.labelOffsetX,
    flyingMode: props.flyingMode,
    closeOnEscape: props.closeOnEscape,
    trapFocus: props.trapFocus,
    restoreFocus: props.restoreFocus,
    lockScroll: props.lockScroll,
    ariaLabel: props.ariaLabel,
    ariaLabelledby: props.ariaLabelledby,
    onGeom: (g) => {
      boxStyle.value = {
        width: `${g.w}px`,
        height: `${g.h}px`,
        top: `${g.top}px`,
        left: `${g.left}px`,
        borderRadius: `${g.radius}px`,
      };
    },
    mount: async () => {
      visible.value = true;
      await nextTick();
    },
    unmount: () => {
      visible.value = false;
      boxStyle.value = {};
    },
    // Único lugar donde se avisa. `open()`/`close()` pueden rebotar contra el
    // guard de reentrada (RNF-2) y el evento saldría igual, mintiendo.
    onState: (s) => {
      if (s === "closed") {
        emit("update:modelValue", false);
        emit("close");
      }
    },
  },
);

// Pide el cierre; el aviso al padre sale de `onState`, no de acá. Emitiendo en
// este punto solo se enteraban los cierres que EMPIEZAN afuera (overlay, ×):
// un cierre que arranca adentro del core —el gesto de arrastre, Escape— dejaba
// el `v-model` en `true` con el panel ya cerrado, y no se podía volver a abrir
// porque el watcher no ve un cambio de `true` a `true`.
const requestClose = () => core.close();

const open = (origin = props.originRef, label = props.label, overrides = {}) => {
  return core.open(origin, label, {
    placement: props.placement,
    align: props.align,
    gap: props.gap,
    ...soloDefinidos({
      duration: props.duration,
      ease: props.ease,
      closeDuration: props.closeDuration,
      closeEase: props.closeEase,
    }),
    contentBlur: props.contentBlur,
    ...overrides,
  });
};

const close = () => core.close();

// Sin `immediate`: se dispararía durante el setup, que en SSR corre en el
// servidor y ahí no hay `document` que medir (RNF-3).
watch(
  () => props.modelValue,
  (isOpen) => (isOpen ? open() : close()),
);
onMounted(() => props.modelValue && open());
onBeforeUnmount(core.destroy);

defineExpose({ open, close, changeView: core.changeView, resync: core.resync });
</script>

// packages/wisspop/src/react/WissPopMorph.jsx
/**
 * Wrapper React de MorphModal — mismo contrato que WissPopMorph.vue.
 *
 * `createPortal` reemplaza a `<Teleport>`, `useRef` reemplaza a `ref()`, y
 * `useImperativeHandle` reemplaza a `defineExpose` (design.md §1). El resto
 * es igual: la geometría entra por `onGeom` a estado reactivo, nunca se
 * escribe `boxEl.style` directo — un re-render de React pisaría a GSAP a
 * mitad de camino, igual que pasaba en Vue (design.md §2).
 */
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { createMorph } from "../core/morph.js";
import { useDomMount } from "./use-dom-mount.js";
import { soloDefinidos } from "../shared/solo-definidos.js";

const CloseIcon = () => (
  <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
    <path d="M18 6 6 18M6 6l12 12" />
  </svg>
);

export const WissPopMorph = forwardRef(function WissPopMorph(
  {
    open: isOpen = false,
    onClose,
    /** HTMLElement | selector CSS | Rect literal */
    originRef = null,
    placement = "center",
    align = "center",
    gap = 16,
    /**
     * Velocidad y curva. Sin default propio A PROPÓSITO: si el wrapper mandara
     * siempre un valor, pisaría al del core y `setDefaults()` no serviría de
     * nada. Sin pasar nada manda el core (0.55 / 0.7, o lo que fije setDefaults).
     * El cierre tiene su propio ritmo: no es la apertura al revés.
     */
    duration,
    ease,
    closeDuration,
    closeEase,
    contentBlur = false,
    /**
     * Texto viajero. `null` (default) no monta nada; con cualquier string
     * —incluso vacío— se crea el elemento que viaja, misma condición que usa
     * `createModal` de vanilla.
     */
    flyingTextClass = null,
    /**
     * Qué viaja del origen al panel: un string o un nodo (se clona, el original
     * se queda en el botón). Es el default del `label` de `open()`, para que el
     * camino declarativo por la prop `open` también pueda tener viajero.
     */
    label = null,
    labelOffsetX = 24,
    /** `"text"` · `"box"` · `null` (automático). Ver DEFAULTS del core. */
    flyingMode = null,
    // Los estilos son del consumidor: la librería solo se ocupa del movimiento.
    modalClass = "",
    overlayClass = "",
    overlay = true,
    overlayBlur = false,
    overlayDark = false,
    // Botón × propio, para cuando no querés armar el tuyo con el `close` del children-render-prop.
    closeButton = false,
    closeButtonClass = "",
    closeOnEscape = true,
    trapFocus = true,
    restoreFocus = true,
    lockScroll = false,
    ariaLabel = null,
    ariaLabelledby = null,
    children,
    /**
     * Todo lo que el wrapper no declara se reenvía al core, igual que el
     * `...coreOpts` de vanilla. Enumerar a mano dejaba opciones afuera en
     * silencio: `swipeToClose` y `fullscreenOnMobile` llegaban `undefined`
     * mientras las demos los pasaban. En React no hace falta normalizar nada:
     * las props ya son camelCase y valores JS reales.
     */
    ...opcionesExtra
  },
  ref,
) {
  const { visible, mount, unmount } = useDomMount();
  const [boxStyle, setBoxStyle] = useState({});
  const boxEl = useRef(null);
  const contentEl = useRef(null);
  const overlayEl = useRef(null);
  const flyingEl = useRef(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;
  // Por ref y no por dependencia del efecto: un nodo como `label` cambia de
  // identidad en cada render y reabriría el panel en loop.
  const labelRef = useRef(label);
  labelRef.current = label;

  // El core se crea UNA sola vez, con las opciones de configuración de ESE
  // primer render — igual que en Vue, no son reactivas a cambios de prop
  // después de montar. Para eso está la API imperativa (`ref.current.open`),
  // que sí acepta overrides por llamada.
  const coreRef = useRef(null);
  if (!coreRef.current) {
    coreRef.current = createMorph(
      {
        box: () => boxEl.current,
        content: () => contentEl.current,
        overlay: () => overlayEl.current,
        flyingText: () => flyingEl.current,
      },
      {
        // Primero: lo que el wrapper cablea explícitamente siempre gana.
        ...opcionesExtra,
        placement,
        align,
        gap,
        ...soloDefinidos({ duration, ease, closeDuration, closeEase }),
        contentBlur,
        labelOffsetX,
        flyingMode,
        closeOnEscape,
        trapFocus,
        restoreFocus,
        lockScroll,
        ariaLabel,
        ariaLabelledby,
        onGeom: (g) =>
          setBoxStyle({
            width: `${g.w}px`,
            height: `${g.h}px`,
            top: `${g.top}px`,
            left: `${g.left}px`,
            borderRadius: `${g.radius}px`,
          }),
        mount,
        unmount: () => {
          unmount();
          setBoxStyle({});
        },
        // Único lugar donde se avisa, para que un cierre que arranca ADENTRO
        // del core —gesto de arrastre, Escape— también baje la prop `open` del
        // padre. Avisando solo desde `requestClose` quedaba en `true` con el
        // panel cerrado, y el efecto no volvía a correr: no se podía reabrir.
        onState: (s) => {
          if (s === "closed") onCloseRef.current?.();
        },
      },
    );
  }

  const requestClose = () => coreRef.current.close();

  useImperativeHandle(
    ref,
    () => ({
      // `(origin, label, overrides)` — misma firma que Vue y que el core, para
      // que el elemento viajero se pueda elegir en la llamada.
      open: (origin, label, overrides) =>
        coreRef.current.open(origin ?? originRef, label ?? labelRef.current, overrides),
      close: () => coreRef.current.close(),
      changeView: (mutate) => coreRef.current.changeView(mutate),
      resync: (duration) => coreRef.current.resync(duration),
      get state() {
        return coreRef.current.state;
      },
    }),
    [originRef],
  );

  // Sin dependencia de `originRef`: igual que el watcher de Vue, solo
  // reacciona a que `isOpen` cambie, pero lee el `originRef` VIGENTE en ese
  // momento (la closure de este efecto se recrea cada render).
  useEffect(() => {
    if (isOpen) {
      coreRef.current.open(originRef, labelRef.current, {
        placement, align, gap, contentBlur,
        ...soloDefinidos({ duration, ease, closeDuration, closeEase }),
      });
    } else {
      coreRef.current.close();
    }
  }, [isOpen, originRef, placement, align, gap, duration, ease, closeDuration, closeEase, contentBlur]);

  useEffect(() => () => coreRef.current.destroy(), []);

  if (typeof document === "undefined") return null; // RNF-3: nada de DOM en SSR

  return createPortal(
    <>
      {visible && overlay && (
        <div
          ref={overlayEl}
          className={`wisspop-overlay ${overlayBlur ? "wisspop-overlay-blur" : ""} ${overlayDark ? "wisspop-overlay-dark" : ""} ${overlayClass}`.trim()}
          onClick={requestClose}
        />
      )}
      {/* Fuera del panel: el panel es overflow-hidden mientras anima y
          recortaría al viajero durante todo el viaje (design.md §6). */}
      {visible && flyingTextClass != null && (
        <div ref={flyingEl} className={`wisspop-flying-text ${flyingTextClass}`} />
      )}
      {visible && (
        <div
          ref={boxEl}
          className={`wisspop-box ${modalClass}`}
          style={boxStyle}
          onClick={(e) => e.stopPropagation()}
        >
          <div ref={contentEl} className="wisspop-content">
            {typeof children === "function" ? children({ close: requestClose }) : children}
          </div>
          {closeButton && (
            <button
              type="button"
              className={`wisspop-close ${closeButtonClass}`}
              aria-label="Cerrar"
              onClick={requestClose}
            >
              <CloseIcon />
            </button>
          )}
        </div>
      )}
    </>,
    document.body,
  );
});
